### ISSUE TITLE
Incorrectly asks for .NET runtime on launch

### ISSUE THREAD

**Issue by MMK21Hub** [ErrorCraft/FunctionAnalyser#1]
## The bug
The application refuses to launch, even if .NET runtime is installed.

## Steps to reproduce
1. Install .NET Runtime
1. Launch the application

## Screenshot
![image](https://user-images.githubusercontent.com/50421330/103622425-a0374a00-4f2e-11eb-993c-fbb359d2fbe4.png)
![image](https://user-images.githubusercontent.com/50421330/103622857-29e71780-4f2f-11eb-8e26-8e52a8467404.png)

**Comment by ErrorCraft** [comment]
Hi, I have seen some other people with the same issue. It should redirect you to [this](https://dotnet.microsoft.com/download/dotnet-core/5.0/runtime/?utm_source=getdotnetcore&utm_medium=referral) page. There you should select the correct version from "Run desktop apps". People might be getting this message because .NET 5 is fairly new. (November 2020)
I'll update the README to include this as well.

**Comment by fludim** [comment]
The same issue happened, so I downloaded and installed .NET version 5.0.101 (the links took me to v3.1 for some reason) and it still asks me to install it, though I had done. This persisted after a system restart.

**Comment by ErrorCraft** [comment]
I released an update, can you check if this solved the problem?

**Comment by MMK21Hub** [comment]
It now runs correctly. 👍
